x-kong-config:
  &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: gateway-db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/gateway_db_password

services:
  placement:
    image: "daprio/dapr"
    container_name: placement
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
    networks:
      - cdim-net
    logging:
      options:
        max-size: 50m

  iam:
    image: quay.io/keycloak/keycloak:26.1
    container_name: iam
    depends_on:
      - iam-db
    command: ["start-dev", "--import-realm"]
    networks:
      - cdim-net
    ports:
      - "8287:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_HOST: iam-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    logging:
      options:
        max-size: 50m
    volumes:
      - "./iam/import:/opt/keycloak/data/import:ro"

  iam-db:
    image: "postgres:16-alpine"
    container_name: iam-db
    volumes:
      - iam-db:/var/lib/postgresql/data
    networks:
      - cdim-net
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/iam_db_password
    secrets:
      - iam_db_password
    logging:
      options:
        max-size: 50m

  gateway:
    image: kong:3.8
    container_name: gateway
    ports:
      - 8014:8000
      - 3514:3500
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
    secrets:
      - gateway_db_password
    depends_on:
      - "gateway-migrate"
    restart: "on-failure:3"
    networks:
      - cdim-net
    logging:
      options:
        max-size: 50m

  gateway-dapr:
    image: daprio/daprd:edge
    container_name: gateway-dapr
    command:
      [
        "./daprd",
        "-app-id","gateway",
        "-app-port","8000",
        "-dapr-http-port","3500",
        "-placement-host-address",
        "placement:50006"
      ]
    depends_on:
      - gateway
      - placement
    network_mode: "service:gateway"
    logging:
      options:
        max-size: 50m

  gateway-migrate:
    image: kong:3.8
    container_name: gateway-migrate
    depends_on:
      - "gateway-db"
    environment:
      <<: *kong-env
    secrets:
      - gateway_db_password
    command: "kong migrations bootstrap"
    restart: "on-failure:3"
    networks:
      - cdim-net
    logging:
      options:
        max-size: 50m

  gateway-db:
    image: "postgres:16-alpine"
    container_name: gateway-db
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/gateway_db_password
    secrets:
      - gateway_db_password
    volumes:
      - gateway-db:/var/lib/postgresql/data
    networks:
      - cdim-net
    logging:
      options:
        max-size: 50m

  message-broker:
    container_name: message-broker
    image: nats:2.10
    ports:
      - "8289:4222"
    command: [ "-c", "/server.conf" ]
    volumes:
      - "./message-broker/configs/server.conf:/server.conf"
      - message-broker:/data/nats/jetstream
    networks:
      - cdim-net
    logging:
      options:
        max-size: 50m

  message-broker-setting:
    container_name: message-broker-setting
    build:
      context: .
      dockerfile: ./message-broker-setting/Dockerfile
    command: >
      sh -c "nats -s message-broker:4222 stream add configuration_manager_hwsync --subjects configuration_manager.hwsync.* --storage file --retention limits --max-msgs 1 --discard old --defaults &&
      nats -s message-broker:4222 stream add layout_apply_apply --subjects layout_apply.apply.* --storage file --retention limits --max-msgs 1 --discard old --defaults"
    depends_on:
      - message-broker
    networks:
      - cdim-net
    logging:
      options:
        max-size: 50m

networks:
  cdim-net:
    external: true

volumes:
  gateway-db:
  iam-db:
  message-broker:

secrets:
  gateway_db_password:
    file: ./gateway-db/secrets/POSTGRES_PASSWORD
  iam_db_password:
    file: ./iam-db/secrets/POSTGRES_PASSWORD
